#!/usr/bin/env bash
set -ex

function build_archs() {
    build_arch
#    for ARCHITECTURE in ${ARCHITECTURES[*]}
#    do
#        build_arch
#    done
}

function build_arch() {
    for VERSION in ${VERSIONS[*]}
    do
        build_version
    done
}

function build_version() {
    for DISTRO in ${DISTROS[*]}
    do
        build_distro
    done
}

function build_distro() {
    for TYPE in ${TYPES[*]}
    do
        build_type
    done
}

function build_type() {
    PLATFORMS=""
    if [[ " ${ARCHITECTURES[@]} " =~ "arm64v8" ]]; then
        PLATFORMS="${PLATFORMS}linux/arm64/v8"
    fi
    if [[ " ${ARCHITECTURES[@]} " =~ "amd64" ]]; then
        if [[ ! -z "$PLATFORMS" ]]; then
            PLATFORMS="${PLATFORMS},"
        fi
        PLATFORMS="${PLATFORMS}linux/amd64"
    fi
    PLATFORMS="${PLATFORMS##*(,)}"
    echo $PLATFORMS
    docker buildx build --platform $PLATFORMS --push --tag hevelop/php:$VERSION-$TYPE-$DISTRO ../dist/$VERSION/$DISTRO/$TYPE
    if [ "$TYPE" = "cli" ]; then
        docker buildx build --platform $PLATFORMS --push --tag hevelop/php:$VERSION-$TYPE-$DISTRO-supervisord ../dist/$VERSION/$DISTRO/$TYPE/supervisord
    fi
}

function push_version() {
    for DISTRO in ${DISTROS[*]}
    do
        push_distro
    done
}

function push_distro() {
    for TYPE in ${TYPES[*]}
    do
        push_type
    done
}

function push_type() {
    docker push hevelop/php:$VERSION-$TYPE-$DISTRO
    if [ "$TYPE" = "cli" ]; then
        docker push hevelop/php:$VERSION-$TYPE-$DISTRO-supervisord
    fi
}

function docker_purge_version() {
    for DISTRO in ${DISTROS[*]}
    do
        docker_purge_distro
    done
}

function docker_purge_distro() {
    for TYPE in ${TYPES[*]}
    do
        docker_purge_type
    done
}

function docker_purge_type() {
    docker rmi hevelop/php:$VERSION-$TYPE-$DISTRO
    #docker rmi php:$VERSION-$TYPE-$DISTRO
    if [ "$TYPE" = "cli" ]; then
        docker rmi hevelop/php:$VERSION-$TYPE-$DISTRO-supervisord
    fi
}

function prepare_archs() {
    for ARCHITECTURE in ${ARCHITECTURES[*]}
    do
        prepare_arch
    done
}

function prepare_arch() {
    for VERSION in ${VERSIONS[*]}
    do
        prepare_version
    done
}

function prepare_version() {
    for DISTRO in ${DISTROS[*]}
    do
        prepare_distro
    done
}

function prepare_distro() {
    for TYPE in ${TYPES[*]}
    do
        prepare_type
    done
}

function prepare_type() {
    mkdir -p ../dist/$ARCHITECTURE/$VERSION/$DISTRO/$TYPE
   if [ "$TYPE" = "cli" ]; then
       CMD="[\"php\", \"-A\"]"
   else
       CMD="[\"php-fpm\", \"-A\"]"
   fi

   CRYPT_LIB=""
   if [ "$DISTRO" = "alpine" ]; then
       if [[ "5.6 7.0 7.1" =~ "$VERSION" ]]; then
           CRYPT_LIB="mcrypt"
       fi
   else
       if [[ "5.6 7.0 7.1" =~ "$VERSION" ]]; then
           CRYPT_LIB="mcrypt"
       fi
   fi
   sed -e "s@%VERSION%@$VERSION@" \
       -e "s@%ARCHITECTURE%@$ARCHITECTURE@" \
	   -e "s@%DISTRO%@$DISTRO@" \
	   -e "s@%TYPE%@$TYPE@" \
	   -e "s@%CMD%@$CMD@" \
	   -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
	   ../templates/docker/Dockerfile-$DISTRO-$TYPE.template > ../dist/$ARCHITECTURE/$VERSION/$DISTRO/$TYPE/Dockerfile

    if [ "$TYPE" = "cli" ]; then
        mkdir -p ../dist/$ARCHITECTURE/$VERSION/$DISTRO/$TYPE/supervisord

        sed -e "s@%VERSION%@$VERSION@" \
            -e "s@%ARCHITECTURE%@$ARCHITECTURE@" \
            -e "s@%DISTRO%@$DISTRO@" \
            -e "s@%TYPE%@$TYPE@" \
            -e "s@%CMD%@$CMD@" \
            -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
            ../templates/docker/Dockerfile-$DISTRO-$TYPE.template > ../dist/$ARCHITECTURE/$VERSION/$DISTRO/$TYPE/supervisord/Dockerfile

        sed -e "s@%VERSION%@$VERSION@" \
            -e "s@%ARCHITECTURE%@$ARCHITECTURE@" \
            -e "s@%DISTRO%@$DISTRO@" \
            -e "s@%TYPE%@$TYPE@" \
            -e "s@%CMD%@$CMD@" \
            -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
            ../templates/docker/Dockerfile-$DISTRO-supervisord.template >> ../dist/$ARCHITECTURE/$VERSION/$DISTRO/$TYPE/supervisord/Dockerfile

        if [[ "$CRYPT_LIB" != "mcrypt" ]]; then
              sed -e "s@%VERSION%@$VERSION@" \
                -e "s@%ARCHITECTURE%@$ARCHITECTURE@" \
                -e "s@%DISTRO%@$DISTRO@" \
                -e "s@%TYPE%@$TYPE@" \
                -e "s@%CMD%@$CMD@" \
                -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
                ../templates/docker/Dockerfile-$DISTRO-sodium.template >> ../dist/$ARCHITECTURE/$VERSION/$DISTRO/$TYPE/supervisord/Dockerfile
        fi

        cp ../templates/supervisord/supervisord.conf ../dist/$ARCHITECTURE/$VERSION/$DISTRO/$TYPE/supervisord/supervisord.conf
    fi

    if [[ "$CRYPT_LIB" != "mcrypt" ]]; then
        sed -e "s@%VERSION%@$VERSION@" \
            -e "s@%ARCHITECTURE%@$ARCHITECTURE@" \
            -e "s@%DISTRO%@$DISTRO@" \
            -e "s@%TYPE%@$TYPE@" \
            -e "s@%CMD%@$CMD@" \
            -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
            ../templates/docker/Dockerfile-$DISTRO-sodium.template >> ../dist/$ARCHITECTURE/$VERSION/$DISTRO/$TYPE/Dockerfile
    fi
}
