#!/usr/bin/env bash
set -e

function build_version() {
    for DISTRO in ${DISTROS[*]}
    do
        build_distro
    done
}

function build_distro() {
    for TYPE in ${TYPES[*]}
    do
        build_type
    done
}

function build_type() {
    docker build  --tag hevelop/php:$VERSION-$TYPE-$DISTRO ../dist/$VERSION/$DISTRO/$TYPE
    if [ "$TYPE" = "cli" ]; then
        docker build --tag hevelop/php:$VERSION-$TYPE-$DISTRO-supervisord ../dist/$VERSION/$DISTRO/$TYPE/supervisord
    fi
}

function push_version() {
    for DISTRO in ${DISTROS[*]}
    do
        push_distro
    done
}

function push_distro() {
    for TYPE in ${TYPES[*]}
    do
        push_type
    done
}

function push_type() {
    docker push hevelop/php:$VERSION-$TYPE-$DISTRO
}

function docker_purge_version() {
    for DISTRO in ${DISTROS[*]}
    do
        docker_purge_distro
    done
}

function docker_purge_distro() {
    for TYPE in ${TYPES[*]}
    do
        docker_purge_type
    done
}

function docker_purge_type() {
    docker rmi hevelop/php:$VERSION-$TYPE-$DISTRO
    #docker rmi php:$VERSION-$TYPE-$DISTRO
    if [ "$TYPE" = "cli" ]; then
        docker rmi hevelop/php:$VERSION-$TYPE-$DISTRO-supervisord
    fi
}

function prepare_version() {
    for DISTRO in ${DISTROS[*]}
    do
        prepare_distro
    done
}

function prepare_distro() {
    for TYPE in ${TYPES[*]}
    do
        prepare_type
    done
}

function prepare_type() {
    mkdir -p ../dist/$VERSION/$DISTRO/$TYPE
   if [ "$TYPE" = "cli" ]; then
       CMD="[\"php\", \"-A\"]"
   else
       CMD="[\"php-fpm\", \"-A\"]"
   fi

   if [ "$DISTRO" = "alpine" ]; then
       if [ "$VERSION" = "7.2" ]; then
           CRYPT_LIB=""
       else
           CRYPT_LIB="mcrypt"
       fi
   else
       if [ "$VERSION" = "7.2" ]; then
           CRYPT_LIB=""
       else
           CRYPT_LIB="mcrypt"
       fi
   fi
   sed -e "s@%VERSION%@$VERSION@" \
	   -e "s@%DISTRO%@$DISTRO@" \
	   -e "s@%TYPE%@$TYPE@" \
	   -e "s@%CMD%@$CMD@" \
	   -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
	   ../templates/docker/Dockerfile-$DISTRO-$TYPE.template > ../dist/$VERSION/$DISTRO/$TYPE/Dockerfile

    if [ "$TYPE" = "cli" ]; then
        mkdir -p ../dist/$VERSION/$DISTRO/$TYPE/supervisord

        sed -e "s@%VERSION%@$VERSION@" \
            -e "s@%DISTRO%@$DISTRO@" \
            -e "s@%TYPE%@$TYPE@" \
            -e "s@%CMD%@$CMD@" \
            -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
            ../templates/docker/Dockerfile-$DISTRO-$TYPE.template > ../dist/$VERSION/$DISTRO/$TYPE/supervisord/Dockerfile

        sed -e "s@%VERSION%@$VERSION@" \
            -e "s@%DISTRO%@$DISTRO@" \
            -e "s@%TYPE%@$TYPE@" \
            -e "s@%CMD%@$CMD@" \
            -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
            ../templates/docker/Dockerfile-$DISTRO-supervisord.template >> ../dist/$VERSION/$DISTRO/$TYPE/supervisord/Dockerfile

        if [[ "$CRYPT_LIB" != "mcrypt" ]]; then
              sed -e "s@%VERSION%@$VERSION@" \
                -e "s@%DISTRO%@$DISTRO@" \
                -e "s@%TYPE%@$TYPE@" \
                -e "s@%CMD%@$CMD@" \
                -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
                ../templates/docker/Dockerfile-$DISTRO-sodium.template >> ../dist/$VERSION/$DISTRO/$TYPE/supervisord/Dockerfile
        fi

        cp ../templates/supervisord/supervisord.conf ../dist/$VERSION/$DISTRO/$TYPE/supervisord/supervisord.conf
    fi

    if [[ "$CRYPT_LIB" != "mcrypt" ]]; then
        sed -e "s@%VERSION%@$VERSION@" \
            -e "s@%DISTRO%@$DISTRO@" \
            -e "s@%TYPE%@$TYPE@" \
            -e "s@%CMD%@$CMD@" \
            -e "s@%CRYPT_LIB%@$CRYPT_LIB@" \
            ../templates/docker/Dockerfile-$DISTRO-sodium.template >> ../dist/$VERSION/$DISTRO/$TYPE/Dockerfile
    fi
}
