#!/usr/bin/env bash
set -ex

#VERSIONS=(7.2 7.0 7.1)
#DISTROS=(alpine stretch)
#TYPES=(cli fpm)

#ARCHITECTURES=(arm64v8)
ARCHITECTURES=(amd64 arm64v8)
VERSIONS=(7.0 7.1 7.2 7.3)
DISTROS=(stretch)
TYPES=(fpm cli)